// attribute section
export const ADD_ATTRIBUTESECTION = 'ADD_ATTRIBUTESECTION';
export const DELETE_ATTRIBUTESECTION = 'DELETE_ATTRIBUTESECTION';
export const EDIT_ATTRIBUTESECTION = 'EDIT_ATTRIBUTESECTION';
export const FIND_ATTRIBUTESECTION = 'FIND_ATTRIBUTESECTION';

// attribute section Search
export const HANDLESEARCHATTRIBUTE = 'HANDLESEARCHATTRIBUTE';
export const HANDLESEARCH = 'HANDLESEARCH';
export const HANDLESEARCHSUCCESS = 'HANDLESEARCHSUCCESS';
export const HANDLESEARCHFAIL = 'HANDLESEARCHFAIL';
export const HANDLESEARCHCHANGES = 'HANDLESEARCHCHANGES';
export const HANDLEREMOVEDATA = 'HANDLEREMOVEDATA';
export const RESETSEARCH = 'RESETSEARCH';

// attribute section delete
export const HANDLEDELETE = 'HANDLEDELETE';
export const HANDLEDELETESUCCESS = 'HANDLEDELETESUCCESS';
export const HANDLEDELETEFAIL = 'HANDLEDELETEFAIL';

//mapping section
export const HANDLEATTRIBUTELIST = 'HANDLEATTRIBUTELIST';
export const HANDLEATTRIBUTELISTSUCCESS = 'HANDLEATTRIBUTELISTSUCCESS';
export const HANDLEATTRIBUTELISTERROR = 'HANDLEATTRIBUTELISTERROR';
export const HANDLEATTRIBUTELISTCHANGES = 'HANDLEATTRIBUTELISTCHANGES';
export const HANDLEMAPPEDCHNAGES = 'HANDLEMAPPEDCHNAGES';
